### ISSUE TITLE
Package `pyb2d`

### ISSUE THREAD

**Issue by jtpio** [emscripten-forge/recipes#117]
Trying to install `pyb2d` for `jupyterlite-xeus-python` with the `XeusPythonEnv.packages` configuration resulted in the following:

```
with channels:
 - https://repo.mamba.pm/emscripten-forge
 - https://repo.mamba.pm/conda-forge
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested pyb2d
-   - nothing provides pysocks >=1.5.6,<2.0,!=1.5.7 needed by urllib3-1.24.3-py_1
```

The motivation is to be able to run the Jupyter Games notebooks from https://github.com/jupyterlite/demo/tree/main/content/pyolite/pyb2d, but with `jupyterlite-xeus-python`.

**Comment by wolfv** [comment]
done!

**Comment by DerThorsten** [comment]
I still need to port https://pypi.org/project/pyb2d-jupyterlite-backend/ st. it works with `pyjs` instead of `pyodide.js` and release this noarch pkg on conda-forge
