### ISSUE TITLE
Emscripten Package Issue

### ISSUE THREAD

**Issue by zachcp** [emscripten-forge/recipes#1246]
I was following the instructions' on @wolfv 's [great post](https://prefix.dev/blog/pixi_wasm) and hit the following issue:

```sh
pixi run build-emscripten-wasm32-pkg  ./recipes/recipes_emscripten/qhull
# Cannot solve the request because of: No candidates were found for emscripten_emscripten-wasm32 3.1.45.*.
```

![image](https://github.com/user-attachments/assets/cf39e417-56a4-4f1e-bf81-893c33203463)

![image](https://github.com/user-attachments/assets/21dc7fac-9b86-4b1d-bd78-357f7809a147)

**Comment by zachcp** [comment]
Looks like theres a `pixi init` that [is needed](https://emscripten-forge.org/development/local_builds/).

**Comment by zachcp** [comment]
Confirming that once pixi init is done, I can build ( or at least the build is in progress )

**Comment by zachcp** [comment]
- Same error.
- Also cannot build the example package, `regex` 

```
# https://emscripten-forge.org/development/local_builds/
# this only needs to be done once
pixi run setup

# this builds the package
pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/regex
```

**Comment by zachcp** [comment]
looks like the emscripten version is newer than the output.  Seems that updating this version in the conda_build_config.yaml yields progress.  Updating that allows the builds to proceed.

```yaml
c_compiler_version:
  - if: emscripten
    then:
      - 3.1.58    // <---- was 3.1.45
  ```

**Comment by zachcp** [comment]
Aaaaand built! Great!

**Comment by zachcp** [comment]
Looks like emscripten is in the processs of [being upgraded](https://github.com/emscripten-forge/recipes/pull/1245). Just bad timing on my part.

**Comment by DerThorsten** [comment]
@zachcp actually the update to emscripten 3.1.58 should not yet be visible to users.
There was a tiny problem that the local builds of the compiler package where already using 3.1.58 (the version in the recipe was already the new one, I change the version in the recipe back to 3.1.45, now local builds should work as expected)

**Comment by DerThorsten** [comment]
@wolfv we could prevent these issues by also uploading the compiler packages for osx-arm64.

**Comment by wolfv** [comment]
Yes, it should be quite straightforward to build them in CI (especially since Github actions has the osx-arm64 runners these days).

**Comment by DerThorsten** [comment]
> Yes, it should be quite straightforward to build them in CI (especially since Github actions has the osx-arm64 runners these days)

we should run this workflow also for mac https://github.com/emscripten-forge/recipes/blob/main/.github/workflows/build_recipes.yaml but only build the packages from the 'recipes/recipes' dir (and **not** 'recipes/recipes_emscrtipten' dir)
and then only upload the packages if they are for osx-arm64 (there are also noarch pkgs in recipes/recipess)
