### ISSUE TITLE
Bzip2 Patch files seems to be incompatible with new rattler-build

### ISSUE THREAD

**Issue by zachcp** [emscripten-forge/recipes#1247]
## Issue

```sh
pixi run build-emscripten-wasm32-pkg  ./recipes/recipes_emscripten/bzip2
# bug: failed to parse entire input. Remaining: ' # To assist in cross-compiling
```

- [Patch code here](https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/bzip2/patches/0001-cross.patch#L8)
- Similar issue in the Rust [patch crate](https://github.com/uniphil/patch-rs/issues/23)
- Current package [looks like it was built 6-12 months ago](https://beta.mamba.pm/channels/emscripten-forge/packages/bzip2). I'm guessing the build system has changed considerably and this will probably come up in other Patch files as well.

**Comment by DerThorsten** [comment]
@zachcp not all packages where rebuild with rattler-build. So they may need some fixing.

I converted all recipes from an old format to rattler-build with some hacky script but could not rebuild any package, that would have been too time-consuming.

**Comment by DerThorsten** [comment]
in the bzip2 case we can just ignore the patches since we build via CMakeLists anyhow, (see https://github.com/emscripten-forge/recipes/pull/1255)
