### ISSUE TITLE
De-List readthedocs.org Build of Archived "Docs" Repository

### ISSUE THREAD

**Issue by michaelweinold** [emscripten-forge/recipes#1269]
Hey, @DerThorsten - you are listed as the sole maintainer of the outdated https://readthedocs.org/projects/emscripten-forge/ site.

The [underlying repo](https://github.com/emscripten-forge/docs) has been archived - but Google still lists it as the first result for searches like "emscripten-forge documentation".

This means that the new https://emscripten-forge.org/ site is a little difficult to find... it would be great if you could de-list the old project. Thank you!

**Comment by DerThorsten** [comment]
I removed the project from RTD.

**Comment by michaelweinold** [comment]
Great, thank you!
