### ISSUE TITLE
package umap-learn

### ISSUE THREAD

**Issue by DerThorsten** [emscripten-forge/recipes#141]
https://pypi.org/project/umap-learn/

**Comment by DerThorsten** [comment]
not sure how easy it will be to hack away numba

**Comment by DerThorsten** [comment]
maybe it is easier to make a pkg from https://github.com/LTLA/umappp

**Comment by wolfv** [comment]
why do we need this so bad?

**Comment by DerThorsten** [comment]
I want this =)

**Comment by DerThorsten** [comment]
(and biologists)
