### ISSUE TITLE
split up scipy

### ISSUE THREAD

**Issue by DerThorsten** [emscripten-forge/recipes#196]
One of the big painpoints wrt python in the browser is the size of packages, in particular the size of `scipy` is annoying.
But `scipy` is a collection of a lot of more or less independent submodules(which should have been individual packages in the first place). Some examples of these sub-package are:
* `scipy.ndimage`
* `scipy.sparse`
* `scipy.fft`
* `scipy.odr`
* `scipy.partial`
*  ...

Most packages which depend on `scipy`, for instance `pandas`, only use a tiny subset of submodules (in the case of `pandas` it is only uses `scipy.sparse`).

What about splitting up `scipy`  in a *main-package* and all the *sub-packages*.The *main-package* would then just depend on all sub-packages. If a package depends on `scipy` it would get the same content as always. But we can change the recipes for packages like `pandas` st. they only depend on the respective subpackages, ie `scipy.sparse`.

**Comment by wolfv** [comment]
I think that should be done by a seperate tool that either performs static or runtime analysis (such as pyodide-pack https://github.com/pyodide/pyodide-pack).
