### ISSUE TITLE
Manual build instructions questions

### ISSUE THREAD

**Issue by rprimet** [emscripten-forge/recipes#217]
Hi,

Since @DerThorsten provided manual build instructions (thanks!), I tried to reproduce those and ran into a few snags, and also have a few questions, so here goes:

### misc. typos (not in shell commands):
"can be build" -> can be built
aftger -> after
localy -> locally
Bootrap -> Bootstrap
popoulate -> populate

### typos in commands
(**note: I used my host install of mamba rather than micromamba, is that possible or not (or discouraged)? Some of the issues may be related to that choice**) -- maybe the answer would entail using docker rather than attempting a build directly on a developer's machine? My choice was guided by the worry that installing micromamba (which is mainly intended for CI?) alongside regular mamba might trample on the host's mamba install...

`ci_env.yaml` -> `ci_env.yml`
`conda create` -> `conda env create` 

(so the env creation command becomes `conda env create -n emforge --file ci_env.yml`)

### issues / malfunctions
- To get the bootstrap build to run, I had to explicitly set the target to emscripten-32, i.e.

`python builder.py build explicit  recipes/recipes_emscripten/bzip2    --skip-tests --emscripten-32`

- Even so, it initially failed
- After the initial failure, I added the local conda channel to my `.condarc` and ran a "full" build (without `--skip-tests`), which ran until the sanity check (run `bzip2 --help`) which failed due to `node` not being found (is there a missing step for activating the emscripten environment?)
- Running the "binary" manually using the emscripten-provided `node` works! 

```
/home/romain/.cache/empack/emsdk-3.1.2/node/14.18.2_64bit/bin/node /home/romain/mambaforge/envs/emforge/conda-bld/bzip2_1668419287752/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/bzip2.js --help
bzip2, a block-sorting file compressor.  Version 1.0.8, 13-Jul-2019.

   usage: bzip2.js [flags and input files in any order]

   -h --help           print this message
   -d --decompress     force decompression
   -z --compress       force compression
   -k --keep           keep (don't delete) input files
   -f --force          overwrite existing output files
   -t --test           test compressed file integrity
   -c --stdout         output to standard out
   -q --quiet          suppress noncritical error messages
   -v --verbose        be verbose (a 2nd -v gives more)
   -L --license        display software version & license
   -V --version        display software version & license
   -s --small          use less memory (at most 2500k)
   -1 .. -9            set block size to 100k .. 900k
   --fast              alias for -1
   --best              alias for -9

   If invoked as `bzip2', default action is to compress.
              as `bunzip2',  default action is to decompress.
              as `bzcat', default action is to decompress to stdout.

   If no file names are given, bzip2 compresses or decompresses
   from standard input to standard output.  You can combine
   short flags, so `-v -4' means the same as -v4 or -4v, &c.

program exited (with status: 0), but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)
```

But fixing this issue would be nice :-)

I can submit a PR, just let me know the answer to the questions and the relevant / irrelevant parts :-)

**Comment by DerThorsten** [comment]
Hi @rprimet,
Thanks for trying this out and sorry for the issues.
I integrated the missing things / fixed some errors.

> After the initial failure, I added the local conda channel to my .condarc and ran a "full" build (without --skip-tests), which ran until the sanity check (run bzip2 --help) which failed due to node not being found (is there a missing step for activating the emscripten environment?)

A bit strange as this works in the CI and on my machines. But we should remove the test which needs `node` anyhow because atm this `node` dependency in the test is not handled by the recipe itself, and we somewhat rely on the systems `node` which is not optimal (https://github.com/emscripten-forge/recipes/pull/219)

**Comment by rprimet** [comment]
Thanks! Closing the issue

**Comment by rprimet** [comment]
Reopening for a few comments:

- Even starting from scratch in a container using micromamba, the bootstrap build (with `--skip-tests`) fails with an error:

```
Solver could not find solution.Mamba failed to solve:
 - bzip2 1.0.8 h494c40a_0

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested bzip2 1.0.8 h494c40a_0
```

which is probably to be expected? But it might be worth warning that this step is expected to fail? (it works after adding the local conda-bld dir as a channel)

- I think micromamba is currently required due to regular `mamba` not providing a `platform` option when running `mamba create`.

**Comment by DerThorsten** [comment]
@rprimet  did you use the following command:
```
python builder.py build explicit  recipes/recipes_emscripten/bzip2   --emscripten-32 --skip-tests
```
which should be visible in the docs
https://emscripten-forge.readthedocs.io/en/latest/src/projects/recipes/local_build.html#bootstrap-build-recipes ?

**Comment by rprimet** [comment]
@DerThorsten yes, I think so, also, it seems to be reproducible by removing the local `conda-bld` channel and re-running the build command

**Comment by DerThorsten** [comment]
> @DerThorsten yes, I think so, also, it seems to be reproducible by removing the local `conda-bld` channel and re-running the build command (at least on my setup, doing so yields an error)

as long as the "non-bootstrap" part works this would be fine

**Comment by rprimet** [comment]
Yes, it does, thanks! (although not right now, because https://repo.mamba.pm seems down -- is there a place to submit an issue?)

**Comment by DerThorsten** [comment]
> Yes, it does, thanks! (although not right now, because https://repo.mamba.pm seems down -- is there a place to submit an issue?)

https://gitter.im/QuantStack/Lobby might be a good place to mention it
