### ISSUE TITLE
Setup Local Build instructions fail for both micromamba & conda [apple silicon]

### ISSUE THREAD

**Issue by tylere** [emscripten-forge/recipes#277]
Working through the [Setup Local Build](https://emscripten-forge.readthedocs.io/en/latest/src/projects/recipes/local_build.html#setup-local-build) docs, I am encountering issues creating the environment.

# micromamba create

Using micromamba to create the environment

`micromamba create -n emforge -f ci_env.yml`

results in 

```
(base) tylere@tylers-mbp recipes % micromamba create -n emforge -f ci_env.yml     

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
microsoft/osx-arm64                                           No change
microsoft/noarch                                              No change
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - nothing provides requested patchelf
      - nothing provides requested playwright
    
    The environment can't be solved, aborting the operation
    
critical libmamba Could not solve for environment specs
```

# conda create

Similarly, using conda to create the environment

`conda env create -n emforge --file ci_env.yml`

results in 

```
(base) tylere@tylers-mbp recipes % conda env create -n emforge --file ci_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - playwright
```

**Comment by tylere** [comment]
Thanks for the feedback. Confirming that I am encountering this using Apple Silicon (M1) device.

**Comment by DerThorsten** [comment]
I got most things working on my M2 with the changes here:

https://github.com/emscripten-forge/recipes/pull/292
I installed playwright via pip and ignored other missing things.

One then needs to build  compilers / cross-python packages by hand, as we only have linux variants of them on emscripten-forge atm:

```
python builder.py build explicit recipes/recipes/emscripten_emscripten-32/
python builder.py build explicit recipes/recipes/cross-python_emscripten-32
```

and then I can build and test emscripten-32 pkgs locally with:
```
python builder.py build explicit recipes/recipes_emscripten/regex  --emscripten-32
```
it should then compile and at the very end you should see:
```
============================= test session starts ==============================
platform emscripten -- Python 3.10.2, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/web_user/recipe_dir
collecting ...
collected 3 items

test_regex.py
.
.
.
                                                        [100%]

============================== 3 passed in 0.04s ===============================
```

**Comment by michaelweinold** [comment]
> https://github.com/emscripten-forge/recipes/issues/277#issuecomment-1466135476:
> One then needs to build compilers / cross-python packages by hand, as we only have linux variants of them on emscripten-forge atm:
>```
>python builder.py build explicit recipes/recipes/emscripten_emscripten-32/
>python builder.py build explicit recipes/recipes/cross-python_emscripten-32#292
>```

@DerThorsten, thank you for the fantastic work around M1/M2 compatibility. Unfortunately, having installed the `emforge` conda environment (with playwright through pip), running:

```
python builder.py build explicit recipes/recipes/emscripten_emscripten-32/   
```

on my M1 MacBook returns the error:

```
Traceback (most recent call last):
  File "/Users/michaelweinold/github/emforge-recipes/builder.py", line 3, in <module>
    from boa.pyapi import py_build
ModuleNotFoundError: No module named 'boa.pyapi'
```

**Comment by michaelweinold** [comment]
> the best thing to do is usualy just check what we are doing in the ci =)

🫡 apologies, I missed the `@python_api` part of the 

```
python -m pip install git+https://github.com/DerThorsten/boa.git@python_api --no-deps --ignore-installed
```

command!

**Comment by DerThorsten** [comment]
no worries..this all very complicated atm =)

**Comment by michaelweinold** [comment]
…am besten Mama vorsichtig bügeln lassen – danke!

Liebe Grüsse,
Michael
