### ISSUE TITLE
Remove the GitHub Pages integration?

### ISSUE THREAD

**Issue by jtpio** [emscripten-forge/recipes#304]
At the moment the repo shows there is a GitHub Pages environment:

![image](https://user-images.githubusercontent.com/591645/229069128-5735724e-f39c-4de5-89b5-cdb378f74391.png)

However it gives a 404:

![image](https://user-images.githubusercontent.com/591645/229069447-ea7b7b94-6d31-4998-8ef2-6aa014ead41c.png)

Also there doesn't seem be a `gh-pages` branch on the repo:

![image](https://user-images.githubusercontent.com/591645/229069368-1df385e7-a478-4744-aaff-9de5f8c12b68.png)

**Comment by DerThorsten** [comment]
thanks for reporting, should be fixed now!

**Comment by jtpio** [comment]
Nice thanks for the fix!
