### ISSUE TITLE
README should contain documentation on how to build recipe locally

### ISSUE THREAD

**Issue by proppy** [emscripten-forge/recipes#452]
Most of the build system seems to be exclusively documented in the github action itself currently:
https://github.com/emscripten-forge/recipes/blob/main/.github/workflows/build_recipes.yaml

It would be nice to provide a script similar to https://github.com/conda-forge/staged-recipes/blob/main/build-locally.py and document the step involved.

**Comment by proppy** [comment]
Seems like:
```
python builder.py  build explicit path/to/recipe
```
do the trick!

**Comment by DerThorsten** [comment]
`--emscripten-32` flag will be needed, ie:

```
python builder.py build explicit recipes/recipes_emscripten/libffi --emscripten-32
```

**Comment by proppy** [comment]
```
nothing provides requested emscripten_emscripten-32
```
do I need to build and install `emscripten_emscripten-32` in the build environment first?

**Comment by DerThorsten** [comment]
what os are you on? for linux you can just add emscripten-forge as channel to your .condarc.
For MacOS you need to build these `https://github.com/emscripten-forge/recipes/tree/main/recipes/recipes` on your machine.
Note that for these compiler packages you do **not** need the flag `-emscripten-32`.

Ie:

```
python builder.py build explicit recipes/recipe/emscripten_emscripte32 
```

Once that's done you  need to add the `conda-build` folder of the env from where you built to your `.condarc`

**Comment by jtpio** [comment]
For reference there are now some instructions for building locally: https://github.com/emscripten-forge/recipes?tab=readme-ov-file#local-builds

Although not sure if they work and/or are up-to-date: https://github.com/emscripten-forge/recipes/issues/811
