### ISSUE TITLE
`HTTP status code: 401` in the quetz upload packages CI step

### ISSUE THREAD

**Issue by jtpio** [emscripten-forge/recipes#457]
Looking at the CI on the latest commit, it looks like the `HTTP status code: 401` in the "quetz upload packages" CI step gives error, but still succeeds to complete.

For example: https://github.com/emscripten-forge/recipes/actions/runs/4967495499/jobs/8889529799

![image](https://github.com/emscripten-forge/recipes/assets/591645/c594e588-e812-44d3-9f58-5e5435811fc0)

<details>
<pre>
Run QUETZ_API_KEY=*** quetz-client https://beta.mamba.pm/channels/emscripten-forge ${CONDA_PREFIX}/conda-bld/emscripten-32/*.tar.bz2 || true
Request failed:
  HTTP status code: 401
  Message: {"detail":"Not logged in"}
Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/ci-env/bin/quetz-client", line 10, in <module>
    sys.exit(main())
  File "/home/runner/micromamba-root/envs/ci-env/lib/python3.10/site-packages/quetz_client/command_line.py", line 73, in main
    files = [('files', open(package, 'rb')) for package in package_file_names]
  File "/home/runner/micromamba-root/envs/ci-env/lib/python3.10/site-packages/quetz_client/command_line.py", line 73, in <listcomp>
    files = [('files', open(package, 'rb')) for package in package_file_names]
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/micromamba-root/envs/ci-env/conda-bld/linux-64/*.tar.bz2'
Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/ci-env/bin/quetz-client", line 10, in <module>
    sys.exit(main())
  File "/home/runner/micromamba-root/envs/ci-env/lib/python3.10/site-packages/quetz_client/command_line.py", line 73, in main
    files = [('files', open(package, 'rb')) for package in package_file_names]
  File "/home/runner/micromamba-root/envs/ci-env/lib/python3.10/site-packages/quetz_client/command_line.py", line 73, in <listcomp>
    files = [('files', open(package, 'rb')) for package in package_file_names]
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/micromamba-root/envs/ci-env/conda-bld/noarch/*.tar.bz2'
</pre>
</details>

**Comment by DerThorsten** [comment]
the "not logged in" seems to be the problematic one.  Not sure whats going on there, but probably the access token expired and we need to generate a new one. I cannot do this atm but on monday

**Comment by jtpio** [comment]
Alright thanks.

The previous commit which updated Xeus Python to `0.15.9` has a similar issue: https://github.com/emscripten-forge/recipes/commit/d78b3f69927548e17984a9e304c2d9404ac8db2b.

Expect the `HTTP status code: 401`, so maybe that's why it was still pushed?

And it appears correctly on the `emscripten-forge` channel:

![image](https://github.com/emscripten-forge/recipes/assets/591645/3ca73d2b-8eb5-4d37-951a-066b611c377b)

**Comment by jtpio** [comment]
Maybe the `QUETZ_API_KEY` token was only valid for one year?

![image](https://github.com/emscripten-forge/recipes/assets/591645/3ca208d3-4004-48cf-a2de-ade28ec715d5)

And setting a new one might be enough to fix it for now.

**Comment by DerThorsten** [comment]
> Maybe the `QUETZ_API_KEY` token was only valid for one year?
> 
> ![image](https://user-images.githubusercontent.com/591645/238143599-3ca208d3-4004-48cf-a2de-ade28ec715d5.png)
> 
> And setting a new one might be enough to fix it for now.

jeah absolutely, that's what I ment with the expired token!

**Comment by DerThorsten** [comment]
the "no such file or directory" error is expected.
We try to upload from the "noarch" folder. If no noarch pkg is build, this will give this error.

https://github.com/emscripten-forge/recipes/blob/aa9e792493eb3afee6afe0a401573e1a08b45d10/.github/workflows/build_recipes.yaml#L142

this is why we have the `  || true ` part .
We should improve the CI st. we just call `QUETZ_API_KEY=${{ secrets.QUETZ_API_KEY}} quetz-client https://beta.mamba.pm/channels/emscripten-forge ${CONDA_PREFIX}/conda-bld/noarch/*.tar.bz2 ` if there is any pkg

**Comment by DerThorsten** [comment]
@jtpio  generated a new key and triggered and added it..the old key was indeed only valid until the 9th of may
