### ISSUE TITLE
Some `conda-forge` Packages missing from `repo.mamba.pm/conda-forge` Channel

### ISSUE THREAD

**Issue by michaelweinold** [emscripten-forge/recipes#460]
Out of our many [Brightway](https://documentation.brightway.dev/) conda-forge packages (eg. [`bw2data`, `bw2io`, `bw2calc`](https://conda-forge.org/feedstock-outputs/index.html), etc.) only `bw2parameters` and `bw2speedups` are available at [beta.mamba.pm/channels/conda-forge](https://beta.mamba.pm/channels/conda-forge?tab=packages&size=25&index=0&query=bw2):

<img width="1127" alt="Screenshot 2023-06-06 at 10 50 49" src="https://github.com/emscripten-forge/recipes/assets/23102087/152c3163-542f-4cdd-9d26-2a4edd712528">

My understanding is that I can't install packages from the default `conda-forge` channel during the build process of the [xeus-python + JupyterLite hub](https://github.com/jupyterlite/xeus-python-demo), instead having to rely on the https://repo.mamba.pm/conda-forge channel.

If this is correct, how can I add our remaining packages?

**Comment by michaelweinold** [comment]
Ah, I see! I would just like to make sure the conda environment file is explicit about which packages have to be installed from emscripten-forge and which ones can be taken from conda-forge. I think we'll go with something along the lines of:

```
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge # check packages at https://beta.mamba.pm/channels
  - conda-forge
  - nodefaults
dependencies:
  # DATA SCIENCE
  - pandas # from channel emscripten-forge
  - numpy # from channel emscripten-forge
  # PLOTTING
  - matplotlib # from channel emscripten-forge
  # BRIGHTWAY DEPENDENCIES (NOT PURE PYTHON)
  - peewee # from channel emscripten-forge (required by brightway)
  - lxml # from channel emscripten-forge (required by brightway)
  # BRIGHTWAY CORE
  - conda-forge::bw2io=0.8.8 # https://anaconda.org/conda-forge/bw2io/files
  - conda-forge::bw2data=3.6.6 # https://anaconda.org/conda-forge/bw2data/files
  - conda-forge::bw2calc=1.8.2 # https://anaconda.org/conda-forge/bw2calc/files
```

**Comment by martinRenou** [comment]
I'm not sure you need to be very specific about the channel.

The channel emscripten-forge being the first in the list, it will have priority over what's in conda-forge.

Only no-arch packages can be pulled from conda-forge, if you try to install other packages NumPy from conda-forge it will complain saying that NumPy is not installable on the emscripten-32 platform.

**Comment by michaelweinold** [comment]
Is NumPy not available on emscripten-32? https://beta.mamba.pm/channels/emscripten-forge/packages/numpy

**Comment by DerThorsten** [comment]
it should be available ( all versions you see at https://beta.mamba.pm/channels/emscripten-forge/packages/numpy are for emscripten-32)

**Comment by martinRenou** [comment]
I highlighted the important part of my comment :)

What I meant is that you don't really need to be specific, your packages will be pulled from the right channel automatically.

**Comment by michaelweinold** [comment]
I see - many thanks, this is clear now!

**Comment by njzjz** [comment]
I got the same issue - the latest pip in https://repo.mamba.pm/conda-forge does not support Python 3.12.

The README is confusing.

https://github.com/emscripten-forge/recipes/blob/f0d72a43e7b907eea7807d20b993cdd613533e8f/README.md?plain=1#L15-L22
