### ISSUE TITLE
Do not use gcc stack guard for macOS / clang compat

### ISSUE THREAD

**Issue by wolfv** [emscripten-forge/recipes#57]
Looks like I cannot link against libsolv because of some GCC stack guard stuff.

According to this: https://stackoverflow.com/a/58873044
We should add `-fno-stack-protector -U_FORTIFY_SOURCE` to `CXXFLAGS`, `CFLAGS` and `LDFLAGS`.

**Comment by wolfv** [comment]
Hmm, actually, it looks like _I_ had to change this locally...

**Comment by DerThorsten** [comment]
I close this as linking to libsolv does not seem to be an issue anymore (I use libsolve for picomamba without problems)
