### ISSUE TITLE
Open to/ready for outside contributions?

### ISSUE THREAD

**Issue by timkpaine** [emscripten-forge/recipes#59]
I have a few packages I build with emscripten (arrow, exprtk), would love to have a unified way to maintain them.

https://github.com/timkpaine/arrow-wasm-cpp
https://github.com/timkpaine/exprtk.js

**Comment by wolfv** [comment]
Note: to speed up builds in your PR, it might be a hotfix to remove other packages from the `packages.json` file (https://github.com/emscripten-forge/recipes/blob/main/packages.json)

**Comment by timkpaine** [comment]
@wolfv nice thanks i'll give it a shot for arrow since ive already seen a fork (@joemarshall) working on pyarrow

**Comment by DerThorsten** [comment]
> Hi @timkpaine yes, that would be great! We're very much open to outside contributions.
> 
> Expect a few hiccups, though. If you create a PR, it will take a pretty long time to build as it currently builds all of the packages in this repo. We'll fix that over the coming days, though.

we fixed that and only new recipes are build, so should be okish fast now

**Comment by rprimet** [comment]
Is there any guide / hints on how to build a new package locally? (e.g. when expecting much fumbling around until getting to a working state :-) maybe using `act` or similar tools?

**Comment by DerThorsten** [comment]
@rprimet  I started to write a section on setting up a local build https://emscripten-forge.readthedocs.io/en/latest/src/projects/recipes/local_build.html#setup-local-build
