### ISSUE TITLE
Remove widgetsnbextension and ipywidgets recipes

### ISSUE THREAD

**Issue by martinRenou** [emscripten-forge/recipes#63]
- [x] Technically the widgetsnbextension recipe can be removed from here when https://github.com/conda-forge/widgetsnbextension-feedstock/issues/52 is fixed
- [ ] The ipywidgets recipe can be removed when it does not depend on ipykernel anymore, or when we have a proper ipykernel recipe for emscripten-32. The ipykernel dependency can be removed if https://github.com/jupyter-xeus/xeus-python/issues/342 is resolved. Removing the ipykernel dependency is a good approach I think, because it will benefit the classic xeus-python and pyolite.

**Comment by martinRenou** [comment]
See https://github.com/jupyter-widgets/ipywidgets/pull/3533 for an approach to remove the ipykernel dependency in ipywidgets

**Comment by jtpio** [comment]
For reference the `ipywidgets` recipe was first removed in https://github.com/emscripten-forge/recipes/pull/298.

But then restored in https://github.com/emscripten-forge/recipes/pull/300 as the `ipykernel` dependency was added back upstream in `ipywidgets` for now. At least for `8.0.x` it seems, might change with `8.x`.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/emscripten-forge/recipes/pull/602, thanks!
