### ISSUE TITLE
Blocking IO requests in xeus-python

### ISSUE THREAD

**Issue by martinRenou** [emscripten-forge/recipes#637]
@martinRenou I had another question that not relevant for this repo, but I can't think where to open an issue:

I want to adapt a library that performs blocking IO to work with emscripten. It's my understanding that it's impossible to perform blocking requests for byte ranges, because this hangs the same event loop that JS uses. Is that correct?

_Originally posted by @agoose77 in https://github.com/emscripten-forge/recipes/issues/636#issuecomment-1716253974_

**Comment by martinRenou** [comment]
> blocking IO to work with emscripten. It's my understanding that it's impossible to perform blocking requests for byte ranges

I don't know how/if that would work. What would it look like in terms of code?

> because this hangs the same event loop that JS uses

This is not correct, because the jupyterlite-xeus-python kernel runs in a web worker, so it does not hang the main thread thankfully. So you can make *e.g.* blocking [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) without freezing the page.

**Comment by agoose77** [comment]
Ah yes, I forgot that the kernel acts in its own worker. That should help immensely. Now just to figure out CORS ;)

**Comment by DerThorsten** [comment]
this is all not needed anymore, the request library should just work
