### ISSUE TITLE
openai / tiktoken (6.9k stars) wanted

### ISSUE THREAD

**Issue by MRYingLEE** [emscripten-forge/recipes#660]
tiktoken (https://github.com/openai/tiktoken) is a must have package for most AI related Python applications.

1. There is no official planning for WebAssembly or pure Python release (https://github.com/openai/tiktoken/issues/94,  https://github.com/openai/tiktoken/issues/134)
2. The codebase consists of Python(68.4%) and Rust (31.6%). Maybe it is easy to be re-compiled to wasm.

Thank you in advance,

**Comment by DerThorsten** [comment]
Feel free to open a PR with a recipe for it

**Comment by DerThorsten** [comment]
tiktoken is now available https://beta.mamba.pm/channels/emscripten-forge/packages/tiktoken
