### ISSUE TITLE
DOC: How to work with emscripten-forge in JupyterLite

### ISSUE THREAD

**Issue by westurner** [emscripten-forge/recipes#699]
- JupyterLite builds its own pyodide and packages.
- JupyterLite presumably can work with emscripten-forge
- What are the good or recommended ways to work with emscripten-forge and micromamba in JupyterLite notebooks?

**Comment by martinRenou** [comment]
For the record, jupyterlite-xeus-python has been deprecated. You now should use jupyterlite-xeux: https://jupyterlite-xeus.readthedocs.io
