### ISSUE TITLE
could we have a little more Operational Research packages in wasm32 ?

### ISSUE THREAD

**Issue by stonebig** [emscripten-forge/recipes#735]
it would be nice to have some Operational Research Packages:
- pyomo is in "emscripten" but not "checked" on the wasm32 column
- jmetalpy seems an option (pure python apparently)
- pymoo + autograd+ cma + alive_progress + dill + contourpy + cycler + packaging + pyparsing + python_dateutil + about_time + graphene  + six ?

**Comment by DerThorsten** [comment]
Feel free to add the recipes
